version: '2'
services:
  nifi-solo:
    image: mkobit/nifi
    ports:
      - "8080-8082:8080-8082"
    volumes:
      - .data/database_repository:/opt/nifi/database_repository
      - .data/flowfile_repository:/opt/nifi/flowfile_repository
      - .data/content_repository:/opt/nifi/content_repository
      - .data/provenance_repository:/opt/nifi/provenance_repository
      - .data/logs:/opt/nifi/logs
