MiNiFi Config Version: 2
Flow Controller:
  name: minifi
  comment: ''
Core Properties:
  flow controller graceful shutdown period: 10 sec
  flow service write delay interval: 500 ms
  administrative yield duration: 30 sec
  bored yield duration: 10 millis
  max concurrent threads: 1
FlowFile Repository:
  partitions: 256
  checkpoint interval: 2 mins
  always sync: false
  Swap:
    threshold: 20000
    in period: 5 sec
    in threads: 1
    out period: 5 sec
    out threads: 4
Content Repository:
  content claim max appendable size: 10 MB
  content claim max flow files: 100
  always sync: false
Provenance Repository:
  provenance rollover time: 1 min
Component Status Repository:
  buffer size: 1440
  snapshot frequency: 1 min
Security Properties:
  keystore: ''
  keystore type: ''
  keystore password: ''
  key password: ''
  truststore: ''
  truststore type: ''
  truststore password: ''
  ssl protocol: ''
  Sensitive Props:
    key:
    algorithm: PBEWITHMD5AND256BITAES-CBC-OPENSSL
    provider: BC
Processors:
- id: 015b1000-e24d-1528-0000-000000000000
  name: TailFile
  class: org.apache.nifi.processors.standard.TailFile
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 1 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    File Location: Local
    File to Tail: /opt/nifi/listeners/exp.txt
    Initial Start Position: Beginning of File
    Rolling Filename Pattern:
Process Groups: []
Input Ports: []
Output Ports: []
Funnels: []
Connections:
- id: 015b1001-e24d-1528-0000-000000000000
  name: TailFile/success/015b100b-2586-1652-8c14-2aa4b5606797
  source id: 015b1000-e24d-1528-0000-000000000000
  source relationship names:
  - success
  destination id: 015b100b-2586-1652-8c14-2aa4b5606797
  max work queue size: 10000
  max work queue data size: 1 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
Remote Process Groups:
- id: 015b100e-2586-1652-0000-000000000000
  name: ''
  url: http://192.168.1.27:8080/nifi
  comment: ''
  timeout: 30 sec
  yield period: 10 sec
  transport protocol: RAW
  Input Ports:
  - id: 015b100b-2586-1652-8c14-2aa4b5606797
    name: Minifi Json
    comment: ''
    max concurrent tasks: 1
    use compression: false
