version: '2'
services:
  zoo1:
    image: zookeeper
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888

  nifi-seed:
    container_name: nifi-cluster-seed
    build: ./base
    command: ["./start-master-nifi.sh"]
    ports:
      - "8080-8082:8080-8082"
    volumes:
      - .data/database_repository:/opt/nifi/database_repository
      - .data/flowfile_repository:/opt/nifi/flowfile_repository
      - .data/content_repository:/opt/nifi/content_repository
      - .data/provenance_repository:/opt/nifi/provenance_repository
    depends_on:
      - zoo1

  nifi-nodes:
    build: ./base
    depends_on:
      - nifi-seed
